"""
verify_filter_coefficients.py
──────────────────────────────
Proves the Arduino hardcoded SOS biquad coefficients match scipy exactly,
then optionally reads the Arduino serial port and classifies each beat
window received via #BEAT_WIN: lines from filter_verify.ino.

Usage:
  # 1. Coefficient verification only (no Arduino needed):
  python deployment/verify_filter_coefficients.py

  # 2. With Arduino connected (filter_verify.ino uploaded):
  python deployment/verify_filter_coefficients.py --port COM3
"""
import sys, argparse, struct
sys.path.insert(0, "c:/p3/cardiac-edge-ai")
import numpy as np
from scipy.signal import butter, sosfilt, sosfilt_zi
import tensorflow as tf
import os
from config import ECG_FS, WINDOW_LEN, TFLITE_DIR, CLASSES

# ── Arduino hardcoded SOS coefficients (from ecg_preprocess.h) ───────────────
# Must match exactly — generated by scipy.signal.butter(2,[0.5,40],fs=360,'sos')
ARDUINO_SOS = np.array([
    # b0          b1          b2          a1           a2
    [0.078762,  0.157525,  0.078762,  -1.067092,  0.384234],   # stage 0
    [1.000000, -2.000000,  1.000000,  -1.987664,  0.987742],   # stage 1
])

def scipy_sos():
    """Compute SOS from scipy for fs=360, bandpass 0.5-40 Hz, order 2."""
    return butter(2, [0.5, 40.0], btype="bandpass", fs=ECG_FS, output="sos")

def verify_coefficients():
    sos = scipy_sos()
    print("=" * 60)
    print("  FILTER COEFFICIENT VERIFICATION")
    print("=" * 60)
    print(f"\n  scipy butter(2, [0.5,40], fs={ECG_FS}):\n")

    # scipy SOS: each row = [b0,b1,b2,1,a1,a2] (note: a0=1 included)
    all_match = True
    for i, (sci, ard) in enumerate(zip(sos, ARDUINO_SOS)):
        sci_b = sci[:3]
        sci_a = sci[4:]   # skip a0=1
        ard_b = ard[:3]
        ard_a = ard[3:]
        print(f"  Stage {i}:")
        print(f"    scipy  b=[{sci_b[0]:.5f}, {sci_b[1]:.5f}, {sci_b[2]:.5f}] "
              f"a=[{sci_a[0]:.5f}, {sci_a[1]:.5f}]")
        print(f"    Arduino b=[{ard_b[0]:.5f}, {ard_b[1]:.5f}, {ard_b[2]:.5f}] "
              f"a=[{ard_a[0]:.5f}, {ard_a[1]:.5f}]")

        b_err = np.max(np.abs(sci_b - ard_b))
        a_err = np.max(np.abs(sci_a - ard_a))
        status = "✅ MATCH" if max(b_err, a_err) < 1e-4 else "❌ MISMATCH"
        print(f"    Max coeff error: b={b_err:.2e}  a={a_err:.2e}  {status}")
        if max(b_err, a_err) >= 1e-4:
            all_match = False

    print(f"\n  Overall: {'✅ All coefficients match!' if all_match else '❌ Coefficient mismatch — update ecg_preprocess.h'}")

    # Impulse response test: same input → same output?
    impulse = np.zeros(200); impulse[0] = 1.0
    scipy_out = sosfilt(scipy_sos(), impulse)

    # Simulate Arduino biquad
    def sim_arduino(x_arr):
        state = [[0.,0.,0.,0.] for _ in range(2)]   # [x1,x2,y1,y2]
        out = []
        for x in x_arr:
            for s in range(2):
                b0,b1,b2,a1,a2 = ARDUINO_SOS[s]
                y = (b0*x + b1*state[s][0] + b2*state[s][1]
                     - a1*state[s][2] - a2*state[s][3])
                state[s][1] = state[s][0]; state[s][0] = x
                state[s][3] = state[s][2]; state[s][2] = y
                x = y
            out.append(y)
        return np.array(out)

    arduino_out = sim_arduino(impulse)
    max_impulse_err = np.max(np.abs(scipy_out - arduino_out))
    print(f"\n  Impulse response max error: {max_impulse_err:.2e}  "
          f"{'✅' if max_impulse_err < 1e-6 else '⚠️'}")
    print("=" * 60)
    return all_match

def run_arduino_verify(port: str):
    """Connect to Arduino filter_verify.ino and classify received beat windows."""
    try:
        import serial
    except ImportError:
        print("[ERR] pyserial not installed. Run: pip install pyserial"); return

    # Load TFLite model
    model_path = os.path.join(TFLITE_DIR, "student_kd_int8.tflite")
    interp = tf.lite.Interpreter(model_path=model_path)
    interp.allocate_tensors()
    inp_d = interp.get_input_details()[0]
    out_d = interp.get_output_details()[0]

    ground_truth = ["N", "AF", "VT", "PVC", "LBBB"]
    beat_num = 0

    print(f"\nConnecting to {port} …")
    with serial.Serial(port, 115200, timeout=10) as ser:
        print(f"Connected. Waiting for beat windows …\n")
        print(f"  {'Beat':<6} {'True':<6} {'Pred':<6} {'Conf':>7}  {'Match'}")
        print(f"  {'-'*40}")

        matches = 0
        total   = 0
        while beat_num < 5:
            line = ser.readline().decode("utf-8", errors="ignore").strip()
            if line.startswith("#BEAT_WIN:"):
                csv_part = line[len("#BEAT_WIN:"):]
                vals = np.array([float(v) for v in csv_part.split(",")])
                if len(vals) != WINDOW_LEN:
                    continue

                # Run TFLite
                x = vals[np.newaxis, :, np.newaxis].astype(np.float32)
                interp.set_tensor(inp_d["index"], x); interp.invoke()
                probs = interp.get_tensor(out_d["index"])[0]
                pred_idx = int(np.argmax(probs))
                conf     = probs[pred_idx] * 100
                true_cls = ground_truth[beat_num] if beat_num < 5 else "?"
                match    = "✅" if CLASSES[pred_idx] == true_cls else "⚠️"
                if CLASSES[pred_idx] == true_cls: matches += 1
                total += 1

                print(f"  {beat_num:<6} {true_cls:<6} {CLASSES[pred_idx]:<6} {conf:>6.1f}%  {match}")
                beat_num += 1

        print(f"\n  Result: {matches}/{total} beats correctly classified")
        if matches >= 3:
            print("  ✅ Arduino filter pipeline verified — ready for CardioEdge.ino")
        else:
            print("  ⚠️  Low accuracy — check electrode placement or re-verify coefficients")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", default=None, help="Arduino COM port (e.g. COM3)")
    args = parser.parse_args()

    ok = verify_coefficients()
    if args.port:
        run_arduino_verify(args.port)
    else:
        print("\n  Tip: Run with --port COM3 to also verify against live Arduino")
