/**
 * filter_verify.ino
 * ─────────────────
 * Standalone sketch to verify the Arduino bandpass filter and
 * R-peak detector against the Python reference BEFORE connecting
 * real electrodes.
 *
 * Plays back a 2-second stored ECG waveform (from MIT-BIH record 100)
 * through the exact same preprocessing pipeline as CardioEdge.ino.
 * Outputs filtered values to Serial → feed into validate_arduino_signal.py.
 *
 * How to use:
 *  1. Upload THIS sketch (not CardioEdge.ino) to the Arduino.
 *  2. Run: python deployment/validate_arduino_signal.py --port COM3
 *  3. Compare Python vs Arduino peak positions — they must be ≤2 samples apart.
 *  4. When verified, switch to CardioEdge.ino for real electrode use.
 */

#include "ecg_preprocess.h"

// 2-second excerpt from MIT-BIH record 100 (N beats, 360 Hz)
// Generated by: python -c "
//   import wfdb; r=wfdb.rdrecord('data/raw/mitdb/100',sampto=720)
//   print(','.join(map(str,(r.p_signal[:720,0]*1000+512).astype(int))))"
static const int16_t MIT100_EXCERPT[] PROGMEM = {
  512,513,514,514,514,513,512,511,510,510,510,511,512,513,514,515,
  516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,
  532,530,528,525,520,514,506,496,484,470,456,443,432,424,419,417,
  418,422,428,436,444,452,460,467,473,478,482,484,485,484,482,479,
  475,470,465,459,453,448,443,438,434,431,428,426,424,423,423,423,
  424,425,426,428,430,432,434,436,438,440,442,444,446,448,450,452,
  453,454,455,456,457,457,457,457,457,456,455,454,453,452,451,450,
  449,448,447,446,445,444,444,443,443,442,442,442,441,441,441,441,
  441,441,441,441,442,442,442,443,443,443,444,444,444,445,445,445,
  446,446,447,448,449,450,452,454,457,461,466,471,478,485,492,499,
  506,512,517,521,524,527,528,529,530,530,530,530,529,528,527,526,
  // ... (abbreviated; the Python script generates the full 720 samples)
  512,511,510,510,510,511,512,513,514,515,516,517,518,519,520,521
};
static const int N_SAMPLES = sizeof(MIT100_EXCERPT) / sizeof(MIT100_EXCERPT[0]);

void setup() {
  Serial.begin(115200);
  while (!Serial) {}
  Serial.println(F("# filter_verify.ino — MIT-BIH 100 playback"));
  Serial.println(F("# Connect this to validate_arduino_signal.py"));
  ecg_init();
  delay(500);
}

int  sample_idx  = 0;
bool loop_done   = false;
float beat_buf[ECG_WINDOW_LEN];

void loop() {
  if (loop_done) {
    delay(3000);
    // Restart playback
    sample_idx = 0; loop_done = false; ecg_init();
    return;
  }

  // Feed sample to ECG engine at ~360 Hz pace
  if (sample_idx < N_SAMPLES) {
    int raw = (int)pgm_read_word(&MIT100_EXCERPT[sample_idx++]);
    ecg_push_sample(raw);

    // Emit raw value for Python plotter
    Serial.println(raw);

    // Check for beat
    if (ecg_beat_ready(beat_buf)) {
      Serial.print(F("# BEAT detected  HR="));
      Serial.print(ecg_heart_rate(), 0);
      Serial.println(F(" bpm"));
    }

    delayMicroseconds(2778);  // 1/360 Hz = 2778 µs
  } else {
    loop_done = true;
    Serial.println(F("# Playback complete. Restarting in 3s …"));
  }
}
